name: Lint JS stuff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint-js:
    name: Lint JS stuff
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('package.lock') }}
          restore-keys: ${{ runner.os }}-npm-dependencies

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependency
        run: pnpm install

      - name: Run JS linter
        run: npm run lint

      - name: Run test
        run: npm run test

      - name: Build_push-image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          cp .env.example .env
          docker login -u ${{ secrets.LOGIN }} -p ${{ secrets.PASS }}
          docker build . -f ./.docker/react/Dockerfile -t ${{ secrets.ACR }}/${{ secrets.APPLICATION }}:latest
          docker push ${{ secrets.ACR }}/${{ secrets.APPLICATION }}:latest
          echo "Deploy successfully!"
